version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    assignees: [ leonidboykov ]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees: [ leonidboykov ]
