name: Go package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Build
        run: go build ./cmd/ddnsman
      - name: Test
        run: go test -v ./...
      - name: Coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      # - name: Kaniko build
      #   uses: aevea/action-kaniko@master
      #   with:
      #     registry: ghcr.io
      #     image: ddnsman
      #     password: ${{ secrets.GITHUB_TOKEN }}
