name: Go package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: ghcr.io
          image: ddnsman
          password: ${{ secrets.GITHUB_TOKEN }}
