name: Multi-Arch Docker Image

on: [push]
# push:
#   branches:
#     - ${{ github.event.repository.default_branch }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        id: setup_qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ steps.setup_qemu.outputs.platforms }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: buildx.Dockerfile
          platforms: ${{ steps.setup_qemu.outputs.platforms }}
          push: true
          tags: leonidboykov/ddnsman:latest
